### ISSUE TITLE
nginx-letsencrypt certificate error

### ISSUE THREAD

**Issue by ghost** [Ilhicas/nginx-letsencrypt#1]
I cloned your project and set it up as on my own server, but I get the following error. How can I fix ?

NET::ERR_CERT_AUTHORITY_INVALID

**Comment by Ilhicas** [comment]
Can you give more information on how you ran it?

You could just do:

```
docker run -e DOMAIN=example.com -e EMAIL=mail@example.com -d -p 80:80 -p 443:443 andreilhicas/nginx-letsencrypt
```

Also make sure domain points to the correct instance/machine runningDocker

**Comment by ghost** [comment]
yes I ran it with the code you typed. no problem, but when I go to the site https://mysite.com gives a certificate error

**Comment by Ilhicas** [comment]
That is because for Nginx to start a fake certificate is issued, until a new one validated by certbot is able to be issued.

Check logs for the container running, and see if certbot was able to issue a certificate.

**Comment by ghost** [comment]
I will recompile and return

**Comment by ghost** [comment]
yes now I re-installed.
When I check the log it gives as follows.
But I ran it the same way you did.


`docker run -e DOMAIN=mysite.com -e EMAIL=mymail@gmail.com -d -p 80:80 -p 443:443 andreilhicas/nginx-letsencrypt`


```
root@dockersystem:~/nginx-letsencrypt# docker logs --details 3196539ca8aa
 Generating RSA private key, 4096 bit long modulus (2 primes)
 ...................................................++++
 ..................................................................................................++++
 e is 65537 (0x010001)
 ./nginx-letsencrypt: line 13: sl: not found
 req: Skipping unknown attribute "EMAIL"
 Signature ok
 subject=C = PT, ST = World, L = World, O = mysite.com, OU = Fiercely lda, CN = mysite.com
 Getting Private key
 Setting up watches.
 Watches established.
 Saving debug log to /var/log/letsencrypt/letsencrypt.log
 Plugins selected: Authenticator webroot, Installer None
 Obtaining a new certificate
 An unexpected error occurred:
 There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains: mysite.com: see https://letsencrypt.org/docs/rate-limits/
 Please see the logfiles in /var/log/letsencrypt for more details.
 173.249.2.122 - - [07/Nov/2019:15:20:02 +0000] "GET / HTTP/1.0" 301 170 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)" "-"
root@dockersystem:~/nginx-letsencrypt# 
```

**Comment by Ilhicas** [comment]
There you have the problem, you requested too many, by abusing LetsEncrypt it will put you on hold.

Read about rate limits for Let'sEncrypt Non Staging Environment:
https://letsencrypt.org/docs/rate-limits/

Each time you destroy and run a new container, you are effectively asking a new Certificate for the same domain.
