### ISSUE TITLE
I am getting some errors, would appreciate your help

### ISSUE THREAD

**Issue by OmarSalka** [Ilhicas/nginx-letsencrypt#4]
Hi,

I have set up everything as instructed and still can't manage to get https to work properly.

The is a snippet of my nginx container's logs:

nginx_1   | Generating RSA private key, 4096 bit long modulus (2 primes)
nginx_1   | ...............++++
nginx_1   | ..........................................++++
nginx_1   | e is 65537 (0x010001)
nginx_1   | req: Skipping unknown attribute "EMAIL"
nginx_1   | Signature ok
nginx_1   | subject=C = PT, ST = World, L = World, O = mywebapp.com, OU = mywebapp, CN = mywebapp.com
nginx_1   | Getting Private key
nginx_1   | Setting up watches.
nginx_1   | Watches established.
nginx_1   | Requested domain  is not a FQDN because it contains an empty label.

Am I doing something wrong? Is there anything I can do to fix this?

**Comment by Ilhicas** [comment]
I'm sorry for late answer, but you probably didn't pass the DOMAIN variable correctly, that response is from certbot

`docker run -e DOMAIN=mysite.com -e EMAIL=mymail@gmail.com -d -p 80:80 -p 443:443 andreilhicas/nginx-letsencrypt`

**Comment by Ilhicas** [comment]
I'm going to close this issue, if you need further help, feel free to reopen this issue
